name         'arjenderijke-monetdb'
version      '0.0.1'
source       'https://github.com/arjenderijke/puppet-monetdb'
author       'arjenderijke'
license      'Apache License, Version 2.0'
summary      'Puppet MonetDB Module'
description  'Puppet module to manage MonetDB RDBMS'
project_page 'https://github.com/arjenderijke/puppet-networkmanager'
dependency   'puppetlabs/stdlib'
